WILL YOU JOIN IIITDMJ?

This is the question we will try to answer today!
I , with Shreyans Katariya have build this basic project. We started with a few basic questions which tried to bring out the sentiments of a student who looks for a college.
This Research Survey was done through Google Form
https://forms.gle/yKgfsfgs3EQuAY4T7

From this we build the dataset provided and build this model.


In [16]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [17]:
a=pd.read_csv("Course-Evaluation-_Responses_.csv")
a.head()

sports  Food  enjoy  final  greneery  placements
0       9     9      7      0         8           9
1       5    10      6      1        10          10
2       8     8      9      0         8           8
3       9    10      9      0        10          10
4       9    10     10      1         9           6

The final column talks about whether the student takes addmission or not as in 0 or 1 , the linear scale rating of this column was changed in excel.

A student will consider College Life , Ambience and placements as most important while choosing a college, this is taken care of.

In [18]:
a=a[["sports","Food","enjoy","greneery","placements","final"]]
b=a[["sports","Food","enjoy","greneery","placements"]]
c=a["final"]

In [19]:
X = b
y = c
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [20]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,y_train)

SVC()

In [21]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.5714285714285714

In [23]:
svm.score(X_test,y_test)

0.7142857142857143

In [24]:
cross_val_score(SVC(gamma='auto'),b,c)


array([0.7       , 0.88888889, 0.66666667, 0.88888889, 0.88888889])

In [27]:
cross_val_score(LogisticRegression(), b, c,cv=3)

array([0.75      , 0.66666667, 0.8       ])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=40),b, c,cv=3)

array([0.6875    , 0.66666667, 0.73333333])

After Cross Validation it is clear that SVM performs the best in prediction.